<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>BattleChess.Rules</AssemblyName>
    <RootNamespace>BattleChess.Rules</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(PackageRootPath)\Rules\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BattleChess.Contracts\BattleChess.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Tests are allowed at internals; the Unity client deliberately is not. -->
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>BattleChess.Core.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
